...E....
======================================================================
ERROR: test_saing_and_retrieving_items (lists.tests.ListAndItemModelsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hadesshark/note-and-code/code/python/TDD/superlists/lists/tests.py", line 31, in test_saing_and_retrieving_items
    list_.save()
AttributeError: 'List' object has no attribute 'save'

----------------------------------------------------------------------
Ran 8 tests in 0.026s

FAILED (errors=1)
