...E
======================================================================
ERROR: test_saing_and_retrieving_items (lists.tests.ItemModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hadesshark/note-and-code/code/python/TDD/superlists/lists/tests.py", line 39, in test_saing_and_retrieving_items
    first_item.save()
AttributeError: 'Item' object has no attribute 'save'

----------------------------------------------------------------------
Ran 4 tests in 0.010s

FAILED (errors=1)
