.......F
======================================================================
FAIL: test_displays_all_items (lists.tests.ListViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hadesshark/note-and-code/code/python/TDD/superlists/lists/tests.py", line 85, in test_displays_all_items
    self.assertContains(response, 'itemey 1')
  File "/usr/local/lib/python3.5/site-packages/django/test/testcases.py", line 350, in assertContains
    response, text, status_code, msg_prefix, html)
  File "/usr/local/lib/python3.5/site-packages/django/test/testcases.py", line 320, in _assert_contains
    " (expected %d)" % (response.status_code, status_code))
AssertionError: 404 != 200 : Couldn't retrieve content: Response code was 404 (expected 200)

----------------------------------------------------------------------
Ran 8 tests in 0.025s

FAILED (failures=1)
