F
======================================================================
FAIL: test_can_start_a_list_and_retriveve_it_later (__main__.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "functional_test.py", line 43, in test_can_start_a_list_and_retriveve_it_later
    self.check_for_row_in_list_table('1: Buy peacock feathers')
  File "functional_test.py", line 17, in check_for_row_in_list_table
    self.assertIn(row_text, [row.text for row in rows])
AssertionError: '1: Buy peacock feathers' not found in []

----------------------------------------------------------------------
Ran 1 test in 6.776s

FAILED (failures=1)
